Add compatibility to API 10.04
PowerAruba/PowerArubaCX pull request #21
Opened 2019-11-28 10:12 UTC by JM2K69

* Add mandatory parameter to Connect-ArubaCX in second position $API
* This function return an $Script:Api for use in other functions 
* Add 3 functions , for Users, Firmware, Vlan

2019-11-28 13:42 UTC, alagoutte commented on PowerArubaCX/Public/Firmware.ps1
> +        current_version   : Virtual.10.04.0001
No need to make a example of display but a description of function (with parameter when it is possible)

2019-11-28 13:48 UTC, alagoutte requested changes
Need some change before merge

2019-11-28 13:48 UTC, alagoutte commented on PowerArubaCX/Public/Connection.ps1
> +        $Script:Api = $Api
move to global variable

2019-11-28 13:48 UTC, alagoutte commented on PowerArubaCX/Public/User.ps1
> +      Get-ArubaCXusers
samewhere

2019-11-28 13:48 UTC, alagoutte commented on PowerArubaCX/Public/interfaces.ps1
> +        $response = $response -replace '%2F','/'
don't replace, it is will complicated when pipeline...

2019-11-28 13:48 UTC, alagoutte commented on PowerArubaCX/Public/ports.ps1
> +        $uri = "rest/$Script:Api/system/ports"
i think move $API directly on Invoke-ArubaCXRestMethod

2019-11-28 13:48 UTC, alagoutte commented on PowerArubaCX/Public/Connection.ps1
> -        $url = "https://${Server}/rest/v1/login"
kept v1 for login

2019-11-28 13:48 UTC, alagoutte commented on PowerArubaCX/Public/Connection.ps1
Add get supported API release (there is a call for this)

2019-11-28 13:48 UTC, alagoutte commented on PowerArubaCX/Public/User.ps1
> +    Param(
no parameter ? depth or other ?

2019-11-28 13:48 UTC, alagoutte commented on PowerArubaCX/Public/vlan.ps1
> +        1                           20
same where... (about example)

2020-01-28 09:20 UTC, closed without merging

2020-01-28 09:20 UTC, JM2K69 commented
Closed